### ISSUE TITLE
do support tuples

### ISSUE THREAD

**Issue by JeffreySarnoff** [Jutho/VectorInterface.jl#3]
This is an always problem/workaround I encounter with "vectorish objects".
Consider points are often represented by one or the other, so a generic point accepting function needs to handle both.
I'd go one half-step farther and support named tuples so `(x= 1.0, y= 2.0)` also works as `Tuple(namedtuple)`

Thanks for the dev effort!

**Comment by Jutho** [comment]
Given that `dot` and `norm` work on them, I am certainly not opposed to this. I leave it open until I have some time.

**Comment by johnnychen94** [comment]
IMO, supporting `Tuple`s alone might not be sufficient. We'll need a mechanism to flexibly extend the concept of "what vector is". This mechanism can be either a trait system or a simple wrapper type. I'm not sure which is better, though.

In addition to the "point", there might also be a real `Point` struct. There are also `RGB`-like colors ([ColorVectorSpace](https://github.com/JuliaGraphics/ColorVectorSpace.jl)) that is neither a `Tuple` or `Vector`. -- `Tuple` sometimes is too generic (has no special meaning) in practice that I'd prefer to avoid.

**Comment by JeffreySarnoff** [comment]
Agree in principle, supporting Tuples is likely more performant if implemented explicitly.
For types like RGB, I have left it to the use to ensure `Tuple(x::T) where T` is well defined and just apply it.
For structs, that works when the struct does not have mixed information; otherwise, the field indices of relevance and in order are needed.

**Comment by Jutho** [comment]
@johnnychen94 , the point of this package is to provide such an interface, like the iterator interface, that hopefully one day any vector-like type in the Julia ecosystem will support. I know this is not very likely if this is not something that is in Base, but one can dream. 

Using an abstract type for this does not work; just like there is no `AbstractIterator` type. There are various types that support iteration, without being subtypes of a common parent. Likewise, while `AbstractArray` might, at first sight, seem a good common supertype for vector-like objects, clearly it is not. There are objects (like those in the ApproxFun ecosystem) that are not subtypes of `AbstractArray`, and there are subtypes of `AbstractArrays` that are not vector-like (e.g. structured arrays with fixed entries one, which can thus not represent a zero or be scaled by constant).

**Comment by Jutho** [comment]
There is now `NamedTuple` support on the main branch; I hope to tag a version 0.2 soon.
